version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/test/test_solidity_project"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/scripts/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/test/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
