name: Dependabot Auto Merge
description: Automatically merge Dependabot PRs when version comparison is within range

branding:
  color: blue
  icon: git-merge

inputs:
  github-token:
    description: The GitHub token used to merge the pull-request
    required: true

  target:
    description: The version comparison target (major, minor, patch)
    default: patch
    required: false

runs:
  using: docker
  image: docker://ahmadnassri/action-dependabot-auto-merge:v1
  env:
    GITHUB_TOKEN: ${{ inputs.github-token }}
    INPUT_TARGET: ${{ inputs.target }}
