[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.vendoring]
destination = "kaprien/_vendor/"
requirements = "kaprien/_vendor/vendor.txt"
namespace = "pip._vendor"

protected-files = ["__init__.py", "README.rst", "vendor.txt"]
patches-dir = "tools/vendoring/patches"

[tool.vendoring.transformations]
substitute = [
  # pkg_resource's vendored packages are directly vendored in pip.
  { match='pkg_resources\.extern', replace="kaprien._vendor" },
  { match='from \.extern', replace="from kaprien._vendor" },
  { match='''\('pygments\.lexers\.''', replace="('kaprien._vendor.pygments.lexers." },
]
drop = []

[tool.vendoring.typing-stubs]
six = ["six.__init__", "six.moves.__init__", "six.moves.configparser"]
distro = []

[tool.vendoring.license.directories]
setuptools = "pkg_resources"

