[build-system]
# hatchling pinned for reproducibility: version should be kept up-to-date
requires = ["hatchling==0.22.0"]
build-backend = "hatchling.build"

[project]
name = "kaprien"
description = 'Demo Package Installer for Kaprien'
readme = "README.rst"
requires-python = ">=3.9"
license = { text = "Apache-2.0"}
keywords = []
authors = [
  { name = "Kairo de Araujo", email = "kairo@dearaujo.nl" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = ["rich-click", "tuf"]
dynamic = ["version"]

[tool.hatch.version]
path = "kaprien/__version__.py"

[project.scripts]
kaprien = "kaprien.cli:kaprien"
