name: CI

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

jobs:
  build-ebpf-exporter-x86_64:
    name: Build ebpf_exporter (x86_64)
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      # Tags are needed for the build version. See:
      # * https://github.com/actions/checkout/issues/206
      - name: Fetch full git history
        run: |
          git fetch --prune --unshallow --tags --force

      - name: Build ebpf_exporter
        run: |
          docker buildx build --progress plain --tag ebpf-exporter-build .
          id=$(docker create ebpf-exporter-build)
          docker cp $id:/usr/sbin/ebpf_exporter ebpf_exporter.x86_64

      - name: Upload ebpf_exporter
        uses: actions/upload-artifact@v2
        with:
          name: ebpf_exporter.x86_64
          path: ebpf_exporter.x86_64

  build-ebpf-exporter-aarch64:
    name: Build ebpf_exporter (aarch64 emulated, be patient)
    runs-on: ubuntu-20.04
    steps:
      - uses: dbhi/qus/action@main
        with:
          targets: aarch64

      - uses: actions/checkout@v2

      # Tags are needed for the build version. See:
      # * https://github.com/actions/checkout/issues/206
      - name: Fetch full git history
        run: |
          git fetch --prune --unshallow --tags --force

      - name: Build ebpf_exporter
        run: |
          docker buildx build --progress plain --tag ebpf-exporter-build --platform linux/arm64 .
          id=$(docker create ebpf-exporter-build)
          docker cp $id:/root/go/bin/ebpf_exporter ebpf_exporter.aarch64

      - name: Upload ebpf_exporter
        uses: actions/upload-artifact@v2
        with:
          name: ebpf_exporter.aarch64
          path: ebpf_exporter.aarch64

  test-ebpf-exporter-x86_64:
    name: Test ebpf_exporter (x86_64)
    needs: build-ebpf-exporter-x86_64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - uses: actions/checkout@v2

      - name: Check vendored dependencies
        run: |
          go mod verify

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

  lint-ebpf-exporter-x86_64:
    name: Lint ebpf_exporter (x86_64)
    needs: build-ebpf-exporter-x86_64
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.50.0
