name: commit-lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: ahmadnassri/action-conventional-commit-lint@v1
        with:
          token: ${{ github.token }}
