# This is a basic workflow to help you get started with Actions

name: Test

on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v2

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install NODE JS
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install testing staff
      run: pip3 install -r test/requirements.txt

    - name: Install geth
      run: |
        sudo add-apt-repository -y ppa:ethereum/ethereum
        sudo apt install ethereum

    - name: Lint python
      run: pylint src
    
    - name: Run tests
      run: |
        pytest --cov=src.predeployed_generator
        bash <(curl -s https://codecov.io/bash) -f .coverage -t $CODECOV_TOKEN || echo "Codecov did not collect coverage reports"    
