name: phpunit
on: [ push ]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [ "7.3", "7.4", "8.0" ]
                laravel: [ "6.0", "7.0", "8.0" ]

        name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip, pcntl, pdo, pdo_sqlite, iconv
                    coverage: xdebug

            -   name: Composer self update
                run: composer self-update

            -   name: Install dependencies
                run: composer require laravel/framework:^${{ matrix.laravel }}

            -   name: Execute tests
                run: |
                    mkdir -p build/logs
                    vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

            -   name: Scrutinizer CI
                if: success() && matrix.php == '8.0' && matrix.laravel == '8.0'
                run: |
                    wget https://scrutinizer-ci.com/ocular.phar
                    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
