name: Tests

on:
    pull_request:
        branches: [master, main]
    push:
        branches: [master, main]

jobs:
    build:
        strategy:
            matrix:
                node: [16.x, 18.x, 20.x]
                os: ['ubuntu-latest', 'windows-2019', 'macos-latest']

        runs-on: ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node }}

            - name: Install Python and build tools
              if: runner.os == 'Linux'
              run: |
                if [[ "${{ runner.os }}" == 'Linux' ]]; then
                sudo apt-get update
                sudo apt-get install -y python3 python3-distutils make g++
                elif [[ "${{ runner.os }}" == 'Windows' ]]; then
                choco install python3 -y
                # Install other required packages for Windows
                elif [[ "${{ runner.os }}" == 'macOS' ]]; then
                brew install python3 g++ make
                fi

            - name: Install Dependencies
              run: npm ci
              env:
                PYTHON: /usr/bin/python3

            - name: Lint the code
              run: npm run lint

            - name: Run tests
              run: npm run test
